
export const SOCKET_EVENT_TRADING_DATAS = 'TRADING_DATAS';

export const SOCKET_EVENT_TRADE_CREATE_RECORD = 'TRADE_CREATE_RECORD';

export const SOCKET_EVENT_TRADE_UPDATE_RECORD = 'TRADE_UPDATE_RECORD';

export const SOCKET_EVENT_TRADE_CHANGE_MESSAGE = 'changed';

export const SOCKET_CLIENT_URL = 'http://localhost:8000'